# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_1_0', '0002_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeuser',
            name='user_articles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='user_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='user_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='user_hometown',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='user_marriage',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='user_selected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='user_signup_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='user_xingzuo',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
