# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_1_0', '0003_auto_20170316_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='user_signup_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
