# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_1_0', '0004_auto_20170316_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
