# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_1_0', '0005_reply_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='down_vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='up_vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
