# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 08:10
from __future__ import unicode_literals

import API_1_0.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_1_0', '0009_auto_20170426_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='occurrence_time',
            field=models.DateTimeField(blank=True, default=API_1_0.models.xlocaltime, null=True),
        ),
    ]
